<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sdl2uml" nsURI="http://www.mdelab.de/mltgg/sdl2uml/1.0" nsPrefix="de.hpi.sam.mote.sdl2uml">
  <eClassifiers xsi:type="ecore:EClass" name="CorrAxiom" eSuperTypes="platform:/plugin/de.mdelab.mltgg.mote2/model/mote2.ecore#//TGGNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CorrConnection" eSuperTypes="platform:/plugin/de.mdelab.mltgg.mote2/model/mote2.ecore#//TGGNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CorrConnectable" eSuperTypes="platform:/plugin/de.mdelab.mltgg.mote2/model/mote2.ecore#//TGGNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CorrProcess" eSuperTypes="#//CorrConnectable"/>
  <eClassifiers xsi:type="ecore:EClass" name="CorrBlock" eSuperTypes="#//CorrConnectable"/>
  <eClassifiers xsi:type="ecore:EClass" name="CorrSystem" eSuperTypes="#//CorrBlock"/>
</ecore:EPackage>
